pictgram/config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'
  
  resources :users
  resources :topics
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete 'cancel', to: 'favorites#cancel' 
end

pictgram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pictgram/app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :topic
end

pictgram/app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  #Topic:user 多 対 1
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  # モデルとの関連付け
  mount_uploader :image, ImageUploader
end

pictgram/app/models/user.rb
class User < ApplicationRecord

validates :name, presence: true
validates :email, presence: true

# password => 長さを8以上32以下
validates :password, length: { in: 8..32 }
# validates :password_confirmation, length: { in: 8..32 }

# パスワード=>アルファベット、数字それぞれ1文字以上含む
VALID_PASSWORD_REGEX =/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
validates :password, format: { with: VALID_PASSWORD_REGEX  }

has_secure_password

#email => ~~@~~.~
VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, format: { with: VALID_EMAIL_REGEX }

# name => 15文字以下
validates :name, length: { maximum: 15 }

#user:topics 1 対 多
has_many :topics
has_many :favorites
has_many :favorite_topics, through: :favorites, source: 'topic'
end

pictgram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  
  add_flash_types :success, :info, :warning, :danger
  
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end

end

pictgram/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def index
    @favorite_topics=current_user.favorite_topics
    # binding.pry
  end

  def create
  
    @favorite=Favorite.new
    # お気に入りを登録するuser_id
    @favorite.user_id=current_user.id
    # お気に入りを登録されるtopic_id
    @favorite.topic_id=params[:topic_id]
    if @favorite.save
      redirect_to topics_path, success: 'お気に入りを登録しました'
    else
      # redirect_to topics_path, danger: 'お気に入りの登録に失敗しました'
      flash.now[:danger]='お気に入りの登録に失敗しました'
    end
  end
  
  
  def cancel
    @favorite=Favorite.find_by(user_id: current_user.id,topic_id: params[:topic_id])
    @favorite.destroy
    redirect_to topics_path, success: 'お気に入りを解除しました'
  end
  
end

pictgram/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

pictgram/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user=User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user #log_inメソッドを実行 userを引数として渡す
      redirect_to root_path, success: 'ログインに成功しました'
        # binding.pry
    else
      flash.now[:danger]='ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out #logoutメソッドを呼び出す
    
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id]=user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil #インスタンス変数
  end
  
  # ストロングパラメータ
  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

pictgram/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic=Topic.new
  end
  
  def create
    @topic=current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '成功しました'
    else
      flash.now[:danger]="投稿に失敗しました"
      render:new
    end
  end
  
  def index
    @topics=Topic.all.includes(:favorite_users)
  end
  
  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

pictgram/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end
  
  def create
    # binding.pry
    # @user=User.new(name: params[:user][:name],email: params[:user][:email])
    @user=User.new(user_params)
    
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger]="登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

pictgram/app/helpers/application_helper.rb
module ApplicationHelper

  # def current_user
  #   @current_user ||=User.find_by(id: session[:user_id])
  # end  

  # def logged_in?
  #   !current_user.nil?
  # end
  
end

pictgram/app/helpers/favorites_helper.rb
module FavoritesHelper
end

pictgram/app/helpers/pages_helper.rb
module PagesHelper
end

pictgram/app/helpers/sessions_helper.rb
module SessionsHelper
end

pictgram/app/helpers/topics_helper.rb
module TopicsHelper
end

pictgram/app/helpers/users_helper.rb
module UsersHelper
end

pictgram/app/views/favorites/index.html.erb
<html>
  
  <div class="topic-index-wrapper">
    <div class="container">
      <% @favorite_topics.each do |topic| %>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="topic-index-single">
              <h2 class="topic-author">
                <%= topic.user.name %>
              </h2>              
               <%= image_tag topic.image.url %>
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% else %>
                <%= link_to cancel_path(topic_id: topic.id), method: :delete do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon favorite' %>
                <% end %>
              <% end %>
              <% if topic.favorite_users.count!=0 %>
                  <p class="favorites_count"><%= topic.favorite_users.count %></p>
                <% end %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              <p class="topic-text">
                <%= topic.description %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  
</html>

pictgram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key,value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
            
          <% else %>
            
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

pictgram/app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

pictgram/app/views/pages/index.html.erb
<!--<h1>Pages#index</h1>-->
<!--<p>Find me in app/views/pages/index.html.erb</p>-->

<html>
  
  <div class="top-hero-wrapper text-center">
    <div class="container top-hero-container">
      <h1 class="text-white">Make you Happy</h1>
      <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
      <div class="row">
        <div class="col-xs-offset-3 col-xs-3">
          <%= link_to 'Sign up', new_user_url, class:'btn btn-block btn-white' %>
        </div>
        <div class="col-xs-3">
          <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %> 
        </div>
      </div>
    </div>
  </div>
  
</html>

pictgram/app/views/topics/index.html.erb
<html>
  <div class="topic-index-wrapper">
    <div class="container">
      <% @topics.each do |topic| %>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="topic-index-single">
              <h2 class="topic-author">
                <%= topic.user.name %>
              </h2>
              <%= image_tag topic.image.url %>
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% else %>
                <%= link_to cancel_path(topic_id: topic.id), method: :delete do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon favorite' %>
                <% end %>
              <% end %>
              <% if topic.favorite_users.count!=0 %>
                  <p class="favorites_count"><%= topic.favorite_users.count %></p>
                <% end %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              <p class="topic-text">
                <%= topic.description %>
                
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</html>

pictgram/app/views/topics/new.html.erb
<html>
  
  <div class="topic-new-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center">Add Picture</h1>
          <%= form_for @topic do |f| %>
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
            
            
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
            
            <% if current_user != nil %>
            
              <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
            
            <% end %>
          
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
  
  
</html>

pictgram/app/views/users/new.html.erb
<!--<h1>Users#new</h1>-->
<!--<p>Find me in app/views/users/new.html.erb</p>-->

<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name,class: 'text-white' %>
            <%= f.text_field :name,class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email,class: 'text-white' %>
            <%= f.text_field :email,class:'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password,class: 'text-white' %>
            <%= f.password_field :password,class:'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password_confirmation,class: 'text-white' %>
            <%= f.password_field :password_confirmation,class:'form-control' %>
          </div>
          
          
          
          <%= f.submit "登録", class:'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path ,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>